version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn git_query.api:app --host 0.0.0.0 --port 8000 --reload 