version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - DEBUG=${DEBUG}
    depends_on:
      - neo4j
    command: uvicorn git_query.api:app --host ${API_HOST} --port ${API_PORT} --reload

  neo4j:
    image: neo4j:5.25.1-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: